### ISSUE TITLE
PHP Critical Error ao adicionar pagamento manual

### ISSUE THREAD

**Issue by subedinfo-it** [moloni-pt/whmcs#2]
Boa tarde,

Ao adicionar um pagamento via manual ao WHMCS (transferencia bancária);
WHMCS
- Billing
 - Unpaid
 - Add Payment (method bank transfer)
 - Transaction ID
- Add Payment

E quando é submetido através de "Add Payment" fica a "pensar" e não passa desta página.

No entanto, verifica-se adicionalmente:
As facturas são marcadas como pagas e a transacção é correctamente registada no WHMCS

É dado um erro PHP:
```
[08-May-2023 17:44:40 Europe/Lisbon] [WHMCS Application] ERROR: TypeError:
Cannot access offset of type string on string in /var/www/sites/proj1ty4/public_html/prod/modules/addons/moloni/src/Moloni/General.php:445
Stack trace:
 #0 /var/www/sites/proj1ty4/public_html/prod/modules/addons/moloni/src/Moloni/General.php(42): Moloni\General->getCurrencyCode() 
 #1 /var/www/sites/proj1ty4/public_html/prod/modules/addons/moloni/hooks.php(15): Moloni\General->createInvoice() 
 #2 [internal function]: WHMCS\Utility\SafeInclude::{closure}() 
 #3 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Hook/Manager.php(0): call_user_func() 
 #4 /var/www/sites/proj1ty4/public_html/prod/vendor/illuminate/support/Facades/Facade.php(261): WHMCS\Hook\Manager->run()
 #5 /var/www/sites/proj1ty4/public_html/prod/includes/functions.php(0): Illuminate\Support\Facades\Facade::__callStatic() 
 #6 /var/www/sites/proj1ty4/public_html/prod/includes/invoicefunctions.php(0): run_hook() 
 #7 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Billing/Invoice.php(0): processPaidInvoice() 
 #8 /var/www/sites/proj1ty4/public_html/prod/includes/invoicefunctions.php(0): WHMCS\Billing\Invoice->addPayment() 
 #9 /var/www/sites/proj1ty4/public_html/prod/op/invoices.php(0): addInvoicePayment() 
 #10 {main} {"exception":"[object] (TypeError(code: 0): Cannot access offset of type string on string at /var/www/sites/proj1ty4/public_html/prod/modules/addons/moloni/src/Moloni/General.php:445)"} []
```

Isto não se verificava na versão anterior e impede as facturas de serem registada na sua totalidade.
Obrigado

**Comment by moloni-pt** [comment]
Bom dia, 

De momento lançámos já a versão 3.3.6 do plugin que pode ser descarregada em: 
https://github.com/moloni-pt/whmcs/releases/tag/v3.3.6 

Esta nova versão deverá já corrigir o erro que indicou e trazer várias melhorias ao nível da gestão de tokens de acesso.

**Comment by subedinfo-it** [comment]
Boa tarde,

Grato pela célere resposta.
Iremos monitorizar e somente daqui por umas semanas teremos novo pagamento manual para efectuar e confirmar a resolução definitiva.
Relativamente à gestão dos tokens de acesso iremos verificar também o comportamento e caso haja necessidade reportaremos essa situação através de diferente issue. Obrigado.
